# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Cbox1 = QtWidgets.QComboBox(self.centralwidget)
        self.Cbox1.setGeometry(QtCore.QRect(60, 90, 211, 22))
        self.Cbox1.setObjectName("Cbox1")
        self.Cbox1.addItem("")
        self.Cbox1.addItem("")
        self.Cbox2 = QtWidgets.QComboBox(self.centralwidget)
        self.Cbox2.setGeometry(QtCore.QRect(60, 140, 211, 22))
        self.Cbox2.setObjectName("Cbox2")
        self.Cbox2.addItem("")
        self.Cbox2.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(120, 200, 81, 26))
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.Cbox1.addItem("2")

        # index = self.Cox1.findText("0", QtCore.Qt.MatchFixedString)

        # self.Cbox1.setCurrentIndex(index)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.submit.clicked.connect(self.pressed)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cbox1.setItemText(0, _translate("MainWindow", "0"))
        self.Cbox1.setItemText(1, _translate("MainWindow", "1"))
        self.Cbox2.setItemText(0, _translate("MainWindow", "0"))
        self.Cbox2.setItemText(1, _translate("MainWindow", "1"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.label.setText(_translate("MainWindow", "X XOR Y = "))

    def pressed(self):
        x = self.Cbox1.currentText()
        y = self.Cbox2.currentText()
        result = int(x)&int(y)
        self.label.setText(f'X XOR Y = {result}')
        self.label.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
