# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(0, 10, 831, 381))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("./img/Tt.png"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.Timetable = QtWidgets.QPushButton(self.centralwidget)
        self.Timetable.setGeometry(QtCore.QRect(100, 410, 81, 26))
        self.Timetable.setText("Timetable")
        self.Timetable.adjustSize()
        self.logo = QtWidgets.QPushButton(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(290, 410, 81, 26))
        self.logo.setText("logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Timetable.clicked.connect(self.show_timetable)
        self.logo.clicked.connect(self.show_logo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Timetable.setText(_translate("MainWindow", "TimeTable"))
        self.logo.setText(_translate("MainWindow", "Logo"))

    def show_timetable(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/Tt.png"))
    
    def show_logo(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/logo.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
