# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(330, 270, 111, 41))
        self.Button1.setObjectName("Button1")
        self.fname = QtWidgets.QLabel(self.centralwidget)
        self.fname.setGeometry(QtCore.QRect(300, 190, 81, 21))
        self.fname.setObjectName("fname")
        self.lname = QtWidgets.QLabel(self.centralwidget)
        self.lname.setGeometry(QtCore.QRect(300, 220, 91, 21))
        self.lname.setObjectName("lname")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPersonal_Information = QtWidgets.QMenu(self.menubar)
        self.menuPersonal_Information.setObjectName("menuPersonal_Information")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuPersonal_Information.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "Submit"))
        self.fname.setText(_translate("MainWindow", "First name : "))
        self.lname.setText(_translate("MainWindow", "Last Name : "))
        self.menuPersonal_Information.setTitle(_translate("MainWindow", "Personal Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
